keys:
  - &skyler D520 AC8D 7C96 9212 5B2B  BD3A 1AFD 1025 6B3C 714D
  - &python_laptop B2EE B25A FB4C 3A2E C7FA  C3A4 3676 C8DC 50D2 4FF6
creation_rules:
  - path_regex: secrets/.*
    key_groups:
      - pgp:
          - *skyler
          - *python_laptop
